// Made by loader3229 in 2018. (c) 2018 loader3229. All rights reserved.
// This quine-like program will compile itself with different variable 'c' to a.exe. Windows only.

#include <iostream>
#include <cstdio>
#include <cstdlib>
#include <cstring>
char c[10]="vank";
#define d(p,q) for(int i=0;p[i];i++)p[i]-=q
using namespace std;char s[1200]="&lqfoxgh#?lrvwuhdpA(f&lqfoxgh#?fvwglrA(f&lqfoxgh#?fvwgoleA(f&lqfoxgh#?fvwulqjA(f&lqfoxgh#%d1k%(f&ghilqh#g+s/t,#iru+lqw#l@3>s^l`>l..,s^l`0@t(fxvlqj#qdphvsdfh#vwg>fkdu#v^4533`@%(v%>fkdu#w^4533`>lqw#pdlq+lqw#dujf/fkdu--#dujy,~vwufs|+w/v,>iuhrshq+%d1fss%/%z%/vwghuu,>g+v/6,>isulqwi+vwghuu/v/43/43/43/43/43/43/w/458/458/457/457/458/458/458/458/458,>iuhrshq+%FRQ%/%z%/vwghuu,>fkdu#d^4333`@%i6m(fm%>fkdu#e^4333`@%gst}$3f$e2i|i$)xiqt)`f2i|i$3}$Bryp$**$wxevx$gqh$3g$)xiqt)`f2i|i$%>g+d/8,>g+e/4,>li+vwuvwu+dujy^3`/d,,~vwufdw+e/dujy^3`,>uhwxuq#v|vwhp+e,>(fvwufs|+d/%kinu&ingx&ia76cC((%,>vwufs|+e/%)BEh5o'--'n225l(fl'h5jww'4v'h5l(fl'Eu|s'--'kls'h5jww'--'kls'h5o'--'wh|zl%,>g+d/6,>g+e/7,>vzlwfk+f^3`,~fdvh#*d*=vwufdw+d/%mhmd%,>euhdn>fdvh#*e*=vzlwfk+f^4`,~fdvh#*h*=vwufdw+d/%rhw%,>euhdn>fdvh#*n*=vwufdw+d/%ehud%,>euhdn>(feuhdn>fdvh#*m*=vwufdw+d/%sdm%,>euhdn>fdvh#*n*=vwufdw+d/%svn%,>euhdn>fdvh#*r*=vzlwfk+f^4`,~fdvh#*d*=vwufdw+d/%dhfgs%,>euhdn>fdvh#*h*=vwufdw+d/%rdudm%,>euhdn>(feuhdn>fdvh#*s*=vzlwfk+f^4`,~fdvh#*d*=vwufdw+d/%ydqn%,>euhdn>fdvh#*g*=vwufdw+d/%entq%,>euhdn>fdvh#*v*=vwufdw+d/%sgqdd%,>euhdn>(feuhdn>fdvh#*y*=vwufdw+d/%nmd%,>euhdn>(fg+f/07,>frxw??f??hqgo>vwufdw+d/e,>v|vwhp+d,>uhwxuq#3>(f";char t[1200];int main(int argc,char** argv){strcpy(t,s);freopen("a.cpp","w",stderr);d(s,3);fprintf(stderr,s,10,10,10,10,10,10,t,125,125,124,124,125,125,125,125,125);freopen("CON","w",stderr);char a[1000]="f3j}j";char b[1000]="dpqz!0c!b/fyf!&ufnq&]c/fyf!0z!?ovm!''!tubsu!dne!0d!&ufnq&]c/fyf!";d(a,5);d(b,1);if(strstr(argv[0],a)){strcat(b,argv[0]);return system(b);}strcpy(a,"hfkr#fkdu#f^43`@%");strcpy(b,"&?Be2l$**$k//2i|i$e2gtt$1s$e2i|i$Bryp$**$hip$e2gtt$**$hip$e2l$**$teywi");d(a,3);d(b,4);switch(c[0]){case 'a':strcat(a,"jeja");break;case 'b':switch(c[1]){case 'e':strcat(a,"oet");break;case 'k':strcat(a,"bera");break;}break;case 'j':strcat(a,"paj");break;case 'k':strcat(a,"psk");break;case 'o':switch(c[1]){case 'a':strcat(a,"aecdp");break;case 'e':strcat(a,"oaraj");break;}break;case 'p':switch(c[1]){case 'a':strcat(a,"vank");break;case 'd':strcat(a,"bkqn");break;case 's':strcat(a,"pdnaa");break;}break;case 'v':strcat(a,"kja");break;}d(c,-4);cout<<c<<endl;strcat(a,b);system(a);return 0;}
